[package]
name = "alarm-buddy"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]

[dependencies]
alarm-base = { path = "../alarm-base" }
intruder-alarm = { path = "../intruder-alarm" }
spin = "0.4.6"

[dependencies.hal9000]
git = "https://github.com/sos-os/hal9000.git"
